services:
  - type: web
    name: cottonworld-fynd-automation
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
